apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-host-pvc
spec:
  volumeName: spark-host-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: ""